language: python
python:
  - "2.7"
install: pip install sphinx
script: sphinx-build -b html -d build/doctrees -c . -W source build/html
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAINWEJWNC6G6AOHZQ
  secret_access_key:
    secure: "l6TvgkMSdApIOs0B1mPT87U0XiHhYG9EhCzyUXi46T54ziVDcJtLes3JviiBhcN2yxcJD8lOe792OGNl4Y/u8jFnnmn4ppj40aTO8ftcQL7vhRte3lq/Kp/+SFHec2yMLFPa9+dXOfUPiKmWc0wtTB5xK55Eq8It6MXmkWtPaky5oc4oglP654ulLxSZpiOZYliOqClztLwgGvrPMbSfa3x+IbqzFTPw4KHP1Ulhmbs0yOByQ7DRA898PhL7wkzrvKWbM9kaq2uuVUx3eaoWClCiVasKN1X1YOHCL9h4HfJ7VO4wM9mnWI6C2KCLQTrNjseibna8qzOpffrGOd4aLo1wmLkhtm/qVLO6J0xlGKrMtWTmBsnzrKUeeAMZ9sJtJTix4NX2ulufP11OIebQif1/Gwxs5Gh7Hwf+GvXnsnjx00hRyedeCYwlTdegXzqnP6Sl8t5LxOeteYMHhtmc762d++Qvyfbrc0Z2PPrqfCQ6Py+tUIB5SsmbbCY8sTQwvZoVwdEQEu0mzh1GtiV/v84Heahn40erY5PvgilVf2156nrMfd+e3ii84m+sjYMiOv43WvD/b5jCETf8aEh28IRYHwb55CUfiOUzpJwoBZAJ3oPHk761B2zbe7t+w4rt1EpGTwlCT9dlm0Zte2iEvwWULpRXRAY+/O4MAI7HKZQ="
  bucket: open5e
  local-dir: build/html
  on:
    repo: eepMoody/open5e
    branch: master
